# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_min', models.DateField(verbose_name='Earliest Date')),
                ('date_max', models.DateField(verbose_name='Latest Date')),
            ],
        ),
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_hits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('team2_hits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Homeruns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_hr', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('team2_hr', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_runs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('team2_runs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(blank=True, max_length=50)),
                ('team2', models.CharField(blank=True, max_length=50)),
                ('winner', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
