# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 17:14
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('findgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(blank=True, max_length=50, verbose_name=b'Team 1')),
                ('team1_runs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Team 1 Runs')),
                ('team1_hits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Team 1 Hits')),
                ('team1_hrs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Team 2 Homeruns')),
                ('home', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team2_name', models.CharField(blank=True, max_length=50, verbose_name=b'Team 2')),
                ('team2_runs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Team 2 Runs')),
                ('team2_hits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Team 2 Hits')),
                ('team2_hrs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Team 2 Homeruns')),
                ('home', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hits',
        ),
        migrations.DeleteModel(
            name='Homeruns',
        ),
        migrations.DeleteModel(
            name='Runs',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.RemoveField(
            model_name='game',
            name='date_max',
        ),
        migrations.RemoveField(
            model_name='game',
            name='date_min',
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.DateField(default=datetime.datetime(2016, 2, 13, 17, 14, 14, 488117, tzinfo=utc), help_text=b'Enter in a year'),
            preserve_default=False,
        ),
    ]
