# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findgames', '0002_auto_20160213_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(help_text=b'Enter in a year'),
        ),
    ]
