# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findgames', '0003_auto_20160213_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FindgamesGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'findgames_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FindgamesTeam1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team1_name', models.CharField(max_length=50)),
                ('team1_runs', models.IntegerField()),
                ('team1_hits', models.IntegerField()),
                ('team1_hrs', models.IntegerField()),
                ('home', models.BooleanField()),
            ],
            options={
                'db_table': 'findgames_team1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FindgamesTeam2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team2_name', models.CharField(max_length=50)),
                ('team2_runs', models.IntegerField()),
                ('team2_hits', models.IntegerField()),
                ('team2_hrs', models.IntegerField()),
                ('home', models.BooleanField()),
            ],
            options={
                'db_table': 'findgames_team2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('post_season', models.TextField(blank=True, null=True)),
                ('stadium', models.TextField(blank=True, null=True)),
                ('team1', models.TextField(blank=True, null=True)),
                ('team2', models.TextField(blank=True, null=True)),
                ('team1_runs', models.TextField(blank=True, null=True)),
                ('team2_runs', models.TextField(blank=True, null=True)),
                ('team1_hits', models.TextField(blank=True, null=True)),
                ('team2_hits', models.TextField(blank=True, null=True)),
                ('team1_hr', models.TextField(blank=True, null=True)),
                ('team2_hr', models.TextField(blank=True, null=True)),
                ('winner', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Team1',
        ),
        migrations.DeleteModel(
            name='Team2',
        ),
    ]
