# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findgames', '0004_auto_20160303_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={},
        ),
    ]
