# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findgames', '0005_auto_20160303_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'managed': False},
        ),
    ]
